import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faCoffee,
    faHome,
    faUser,
    faEnvelope,
    faHeart,
    faGlobe,
    faClock,
    faCaretDown,
    faGear,
    faBars,
    faXmark,
    faSearch,
    faTimes,
    faArrowDown19,
    faArrowUp91,
    faRotate,
    faAdd,
    faPenToSquare,
    faTrashCan,
    faCaretLeft,
    faCaretRight,
    faCalendar,
    faFileExcel,
    faFilePdf,
    faFolderPlus,
    faSave,
    faDownload,
    faBuildingColumns,
    faFontAwesome,
    faLocation,
    faLocationDot,
    faMapLocation,
    faStreetView,
    faBowlFood,
    faBoxesPacking,
   
} from '@fortawesome/free-solid-svg-icons';


// Agregar todos los iconos a la librería de FontAwesome
library.add(
    faCoffee,
    faHome,
    faUser,
    faEnvelope,
    faHeart,
    faGlobe,
    faClock,
    faCaretDown,
    faGear,
    faBars,
    faXmark,
    faSearch,
    faTimes,
    faArrowDown19,
    faArrowUp91,
    faRotate,
    faAdd,
    faPenToSquare,
    faTrashCan,
    faCaretLeft,
    faCaretRight,
    faCalendar,
    faFileExcel,
    faDownload,
    faBuildingColumns,
    faFontAwesome,
    faLocation,
    faLocationDot,
    faMapLocation,
    faStreetView,
    faBowlFood,
    faBoxesPacking

);

export const ICONS = {
    coffee: faCoffee,
    home: faHome,
    user: faUser,
    envelope: faEnvelope,
    heart: faHeart,
    globe: faGlobe,
    clock: faClock,
    caretDown: faCaretDown,
    gear: faGear,
    bars: faBars,
    xmark: faXmark,
    search: faSearch,
    times: faTimes,
    arrowDown19: faArrowDown19,
    arrowUp91: faArrowUp91,
    rotate: faRotate,
    add: faAdd,
    penToSquare: faPenToSquare,
    trashCan: faTrashCan,
    caretLeft: faCaretLeft,
    caretRight: faCaretRight,
    calendar: faCalendar,
    fileExcel: faFileExcel,
    filePdf: faFilePdf,
    folderPlus: faFolderPlus,
    arrowLeft: faCaretLeft,
    save: faSave,
    download: faDownload,
    buildingColumns: faBuildingColumns,
    fontAwesomeIcon: faFontAwesome,
    location: faLocation,
    locationDot: faLocationDot,
    mapLocation: faMapLocation,
    streetView: faStreetView,
    bowlFood: faBowlFood,
    boxesPacking: faBoxesPacking



};
